## 01. Neural network regression with TensorFlow Exercises

### Create your own regression dataset (or make the one we created in "Create data to view and fit" bigger) and build fit a model to it.

In [5]:
import numpy as np
X = [i for i in range(-100,500, 3)]
X = np.array(X)
X

array([-100,  -97,  -94,  -91,  -88,  -85,  -82,  -79,  -76,  -73,  -70,
        -67,  -64,  -61,  -58,  -55,  -52,  -49,  -46,  -43,  -40,  -37,
        -34,  -31,  -28,  -25,  -22,  -19,  -16,  -13,  -10,   -7,   -4,
         -1,    2,    5,    8,   11,   14,   17,   20,   23,   26,   29,
         32,   35,   38,   41,   44,   47,   50,   53,   56,   59,   62,
         65,   68,   71,   74,   77,   80,   83,   86,   89,   92,   95,
         98,  101,  104,  107,  110,  113,  116,  119,  122,  125,  128,
        131,  134,  137,  140,  143,  146,  149,  152,  155,  158,  161,
        164,  167,  170,  173,  176,  179,  182,  185,  188,  191,  194,
        197,  200,  203,  206,  209,  212,  215,  218,  221,  224,  227,
        230,  233,  236,  239,  242,  245,  248,  251,  254,  257,  260,
        263,  266,  269,  272,  275,  278,  281,  284,  287,  290,  293,
        296,  299,  302,  305,  308,  311,  314,  317,  320,  323,  326,
        329,  332,  335,  338,  341,  344,  347,  3

In [6]:
y = X + 3
y

array([-97, -94, -91, -88, -85, -82, -79, -76, -73, -70, -67, -64, -61,
       -58, -55, -52, -49, -46, -43, -40, -37, -34, -31, -28, -25, -22,
       -19, -16, -13, -10,  -7,  -4,  -1,   2,   5,   8,  11,  14,  17,
        20,  23,  26,  29,  32,  35,  38,  41,  44,  47,  50,  53,  56,
        59,  62,  65,  68,  71,  74,  77,  80,  83,  86,  89,  92,  95,
        98, 101, 104, 107, 110, 113, 116, 119, 122, 125, 128, 131, 134,
       137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167, 170, 173,
       176, 179, 182, 185, 188, 191, 194, 197, 200, 203, 206, 209, 212,
       215, 218, 221, 224, 227, 230, 233, 236, 239, 242, 245, 248, 251,
       254, 257, 260, 263, 266, 269, 272, 275, 278, 281, 284, 287, 290,
       293, 296, 299, 302, 305, 308, 311, 314, 317, 320, 323, 326, 329,
       332, 335, 338, 341, 344, 347, 350, 353, 356, 359, 362, 365, 368,
       371, 374, 377, 380, 383, 386, 389, 392, 395, 398, 401, 404, 407,
       410, 413, 416, 419, 422, 425, 428, 431, 434, 437, 440, 44

### Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

In [22]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

tf.random.set_seed(42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = tf.constant(X_train)
y_train = tf.constant(y_train)
# 1. Create the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1),
])

# 2. Compile the model
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["mae"])

# 3. Fit the model
model.fit(tf.expand_dims(X_train, axis=1), y_train, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 140.5794 - mae: 140.5794
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 28.1316 - mae: 28.1316
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 30.4377 - mae: 30.4377
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 32.0266 - mae: 32.0266
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 20.7406 - mae: 20.7406
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 20.4753 - mae: 20.4753
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 15.4798 - mae: 15.4798
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 12.1902 - mae: 12.1902
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 5.6040 - mae: 5.6040
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 6.5569 - mae: 6.5569
Epoch 11/100
5/5 [==============================] - 0s 3ms/st

In [23]:
model.evaluate(tf.expand_dims(tf.constant(X_test), axis=1), tf.constant(y_test))

2/2 [==============================] - 0s 4ms/step - loss: 6.9941 - mae: 6.9941


[6.9940595626831055, 6.9940595626831055]

### Try and improve the results we got on the insurance dataset, some things you might want to try include:


#### Building a larger model (how does one with 4 dense layers go?).

In [20]:
# 1. Create the model
larger_model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000),
    tf.keras.layers.Dense(500),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1),
])

# 2. Compile the model
larger_model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["mae"])

# 3. Fit the model
larger_model.fit(tf.expand_dims(X_train, axis=1), y_train, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 6ms/step - loss: 132.6660 - mae: 132.6660
Epoch 2/100
5/5 [==============================] - 0s 5ms/step - loss: 36.6433 - mae: 36.6433
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 12.7996 - mae: 12.7996
Epoch 4/100
5/5 [==============================] - 0s 5ms/step - loss: 17.5519 - mae: 17.5519
Epoch 5/100
5/5 [==============================] - 0s 5ms/step - loss: 23.7107 - mae: 23.7107
Epoch 6/100
5/5 [==============================] - 0s 9ms/step - loss: 28.8267 - mae: 28.8267
Epoch 7/100
5/5 [==============================] - 0s 6ms/step - loss: 19.5655 - mae: 19.5655
Epoch 8/100
5/5 [==============================] - 0s 5ms/step - loss: 14.8488 - mae: 14.8488
Epoch 9/100
5/5 [==============================] - 0s 5ms/step - loss: 26.6627 - mae: 26.6627
Epoch 10/100
5/5 [==============================] - 0s 5ms/step - loss: 8.6755 - mae: 8.6755
Epoch 11/100
5/5 [==============================] - 0s 5ms/

In [21]:
larger_model.evaluate(tf.expand_dims(tf.constant(X_test), axis=1), tf.constant(y_test))

2/2 [==============================] - 0s 3ms/step - loss: 7.8479 - mae: 7.8479


[7.847922325134277, 7.847922325134277]

#### Increasing the number of units in each layer.


In [18]:
# 1. Create the model
larger_model = tf.keras.Sequential([
    tf.keras.layers.Dense(1500),
    tf.keras.layers.Dense(1000),
    tf.keras.layers.Dense(500),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(1),
])

# 2. Compile the model
larger_model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["mae"])

# 3. Fit the model
larger_model.fit(tf.expand_dims(X_train, axis=1), y_train, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 12ms/step - loss: 384.9614 - mae: 384.9614
Epoch 2/100
5/5 [==============================] - 0s 12ms/step - loss: 166.5948 - mae: 166.5948
Epoch 3/100
5/5 [==============================] - 0s 12ms/step - loss: 51.8987 - mae: 51.8987
Epoch 4/100
5/5 [==============================] - 0s 12ms/step - loss: 79.4648 - mae: 79.4648
Epoch 5/100
5/5 [==============================] - 0s 12ms/step - loss: 26.2583 - mae: 26.2583
Epoch 6/100
5/5 [==============================] - 0s 12ms/step - loss: 21.4862 - mae: 21.4862
Epoch 7/100
5/5 [==============================] - 0s 12ms/step - loss: 30.2300 - mae: 30.2300
Epoch 8/100
5/5 [==============================] - 0s 12ms/step - loss: 15.8643 - mae: 15.8643
Epoch 9/100
5/5 [==============================] - 0s 13ms/step - loss: 30.1164 - mae: 30.1164
Epoch 10/100
5/5 [==============================] - 0s 12ms/step - loss: 35.9340 - mae: 35.9340
Epoch 11/100
5/5 [===========================

In [19]:
larger_model.evaluate(tf.expand_dims(tf.constant(X_test), axis=1), tf.constant(y_test))

2/2 [==============================] - 0s 4ms/step - loss: 4.1378 - mae: 4.1378


[4.137758731842041, 4.137758731842041]

#### Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?


In [16]:
# 1. Create the model
larger_model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000),
    tf.keras.layers.Dense(500),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1),
])

# 2. Compile the model
larger_model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(lr=0.01),
              metrics=["mae"])

# 3. Fit the model
larger_model.fit(tf.expand_dims(X_train, axis=1), y_train, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 4ms/step - loss: 127.5771 - mae: 127.5771
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 35.5171 - mae: 35.5171
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 38.0219 - mae: 38.0219
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 38.5177 - mae: 38.5177
Epoch 5/100
5/5 [==============================] - 0s 8ms/step - loss: 20.2179 - mae: 20.2179
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 24.2037 - mae: 24.2037
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 29.7424 - mae: 29.7424
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 23.1634 - mae: 23.1634
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 27.2267 - mae: 27.2267
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 21.3920 - mae: 21.3920
Epoch 11/100
5/5 [==============================] - 0s 10

In [17]:
larger_model.evaluate(tf.expand_dims(tf.constant(X_test), axis=1), tf.constant(y_test))

2/2 [==============================] - 0s 5ms/step - loss: 8.2488 - mae: 8.2488


[8.248753547668457, 8.248753547668457]

#### What happens if you train for longer (say 300 epochs instead of 200)?

In [13]:
# 1. Create the model
larger_model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000),
    tf.keras.layers.Dense(500),
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1),
])

# 2. Compile the model
larger_model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(lr=0.01),
              metrics=["mae"])

# 3. Fit the model
larger_model.fit(tf.expand_dims(X_train, axis=1), y_train, epochs=300)

Epoch 1/300
5/5 [==============================] - 1s 5ms/step - loss: 193.1698 - mae: 193.1698
Epoch 2/300
5/5 [==============================] - 0s 4ms/step - loss: 139.2572 - mae: 139.2572
Epoch 3/300
5/5 [==============================] - 0s 5ms/step - loss: 97.5379 - mae: 97.5379
Epoch 4/300
5/5 [==============================] - 0s 4ms/step - loss: 85.2198 - mae: 85.2198
Epoch 5/300
5/5 [==============================] - 0s 4ms/step - loss: 19.3328 - mae: 19.3328
Epoch 6/300
5/5 [==============================] - 0s 4ms/step - loss: 10.6226 - mae: 10.6226
Epoch 7/300
5/5 [==============================] - 0s 5ms/step - loss: 10.2710 - mae: 10.2710
Epoch 8/300
5/5 [==============================] - 0s 5ms/step - loss: 7.0621 - mae: 7.0621
Epoch 9/300
5/5 [==============================] - 0s 9ms/step - loss: 12.7919 - mae: 12.7919
Epoch 10/300
5/5 [==============================] - 0s 5ms/step - loss: 9.2845 - mae: 9.2845
Epoch 11/300
5/5 [==============================] - 0s 5ms/

In [14]:
larger_model.evaluate(tf.expand_dims(tf.constant(X_test), axis=1), tf.constant(y_test))

2/2 [==============================] - 0s 4ms/step - loss: 4.4447 - mae: 4.4447


[4.444724082946777, 4.444724082946777]

### Import the Boston pricing dataset from TensorFlow tf.keras.datasets and model it.

In [26]:
data = tf.keras.datasets.boston_housing.load_data(
    path='boston_housing.npz', test_split=0.2, seed=113
)
data

((array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
          3.96900e+02, 1.87200e+01],
         [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
          3.95380e+02, 3.11000e+00],
         [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
          3.75520e+02, 3.26000e+00],
         ...,
         [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
          3.62250e+02, 7.83000e+00],
         [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
          2.61950e+02, 1.57900e+01],
         [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
          3.76700e+02, 4.38000e+00]]),
  array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
         17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
         32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
         23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
         12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.

In [28]:
(X_train, y_train), (X_test, y_test) = data
X_train = tf.constant(X_train)
y_train = tf.constant(y_train)
X_test = tf.constant(X_test)
y_test = tf.constant(y_test)
X_train, y_train

(<tf.Tensor: shape=(404, 13), dtype=float64, numpy=
 array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
         3.96900e+02, 1.87200e+01],
        [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
         3.95380e+02, 3.11000e+00],
        [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
         3.75520e+02, 3.26000e+00],
        ...,
        [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
         3.62250e+02, 7.83000e+00],
        [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
         2.61950e+02, 1.57900e+01],
        [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
         3.76700e+02, 4.38000e+00]])>,
 <tf.Tensor: shape=(404,), dtype=float64, numpy=
 array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
        17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
        32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
        23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. ,

#### First model: 3 hidden layers, epochs 100

In [29]:
# 1. Create the model
boston_pricing_model = tf.keras.Sequential([
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
boston_pricing_model.compile(loss=tf.keras.losses.mae,
                             optimizer=tf.keras.optimizers.Adam(),
                             metrics=["mae"])

# 3. Fit the model
boston_pricing_model.fit(tf.expand_dims(X_train, axis=1), y_train, epochs=100)

Epoch 1/100
13/13 [==============================] - 1s 2ms/step - loss: 23.4700 - mae: 23.4700
Epoch 2/100
13/13 [==============================] - 0s 1ms/step - loss: 11.7281 - mae: 11.7281
Epoch 3/100
13/13 [==============================] - 0s 1ms/step - loss: 9.7235 - mae: 9.7235
Epoch 4/100
13/13 [==============================] - 0s 1ms/step - loss: 9.2793 - mae: 9.2793
Epoch 5/100
13/13 [==============================] - 0s 1ms/step - loss: 8.5027 - mae: 8.5027
Epoch 6/100
13/13 [==============================] - 0s 1ms/step - loss: 7.9634 - mae: 7.9634
Epoch 7/100
13/13 [==============================] - 0s 1ms/step - loss: 7.8642 - mae: 7.8642
Epoch 8/100
13/13 [==============================] - 0s 1ms/step - loss: 8.6651 - mae: 8.6651
Epoch 9/100
13/13 [==============================] - 0s 1ms/step - loss: 10.1576 - mae: 10.1576
Epoch 10/100
13/13 [==============================] - 0s 1ms/step - loss: 8.5022 - mae: 8.5022
Epoch 11/100
13/13 [==============================] -

In [30]:
# Evaluate model
boston_pricing_model.evaluate(tf.expand_dims(X_test, axis=1), y_test)

4/4 [==============================] - 0s 2ms/step - loss: 6.9612 - mae: 6.9612


[6.961247444152832, 6.961247444152832]

In [31]:
boston_pricing_model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_48 (Dense)            (None, 1, 100)            1400      
                                                                 
 dense_49 (Dense)            (None, 1, 10)             1010      
                                                                 
 dense_50 (Dense)            (None, 1, 1)              11        
                                                                 
Total params: 2421 (9.46 KB)
Trainable params: 2421 (9.46 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


#### Second model: 3 hidden layers, epochs 200

In [32]:
# 1. Create the model
boston_pricing_model = tf.keras.Sequential([
    tf.keras.layers.Dense(100),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
boston_pricing_model.compile(loss=tf.keras.losses.mae,
                             optimizer=tf.keras.optimizers.Adam(),
                             metrics=["mae"])

# 3. Fit the model
boston_pricing_model.fit(tf.expand_dims(X_train, axis=1), y_train, epochs=200)

Epoch 1/200
13/13 [==============================] - 0s 2ms/step - loss: 52.5668 - mae: 52.5668
Epoch 2/200
13/13 [==============================] - 0s 2ms/step - loss: 17.7124 - mae: 17.7124
Epoch 3/200
13/13 [==============================] - 0s 1ms/step - loss: 10.0443 - mae: 10.0443
Epoch 4/200
13/13 [==============================] - 0s 1ms/step - loss: 8.6154 - mae: 8.6154
Epoch 5/200
13/13 [==============================] - 0s 1ms/step - loss: 8.0719 - mae: 8.0719
Epoch 6/200
13/13 [==============================] - 0s 1ms/step - loss: 7.9397 - mae: 7.9397
Epoch 7/200
13/13 [==============================] - 0s 1ms/step - loss: 8.0453 - mae: 8.0453
Epoch 8/200
13/13 [==============================] - 0s 1ms/step - loss: 7.5034 - mae: 7.5034
Epoch 9/200
13/13 [==============================] - 0s 1ms/step - loss: 7.5949 - mae: 7.5949
Epoch 10/200
13/13 [==============================] - 0s 1ms/step - loss: 7.3289 - mae: 7.3289
Epoch 11/200
13/13 [==============================] -

In [33]:
# Evaluate model
boston_pricing_model.evaluate(tf.expand_dims(X_test, axis=1), y_test)

4/4 [==============================] - 0s 2ms/step - loss: 7.0438 - mae: 7.0438


[7.043759346008301, 7.043759346008301]

#### Third model: increase hidden unit layer

In [34]:
# 1. Create the model
boston_pricing_model = tf.keras.Sequential([
    tf.keras.layers.Dense(1000),
    tf.keras.layers.Dense(500),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
boston_pricing_model.compile(loss=tf.keras.losses.mae,
                             optimizer=tf.keras.optimizers.Adam(),
                             metrics=["mae"])

# 3. Fit the model
boston_pricing_model.fit(tf.expand_dims(X_train, axis=1), y_train, epochs=200)

Epoch 1/200
13/13 [==============================] - 0s 4ms/step - loss: 176.8090 - mae: 176.8090
Epoch 2/200
13/13 [==============================] - 0s 4ms/step - loss: 61.5594 - mae: 61.5594
Epoch 3/200
13/13 [==============================] - 0s 4ms/step - loss: 20.9109 - mae: 20.9109
Epoch 4/200
13/13 [==============================] - 0s 4ms/step - loss: 20.5014 - mae: 20.5014
Epoch 5/200
13/13 [==============================] - 0s 4ms/step - loss: 22.9632 - mae: 22.9632
Epoch 6/200
13/13 [==============================] - 0s 4ms/step - loss: 19.6013 - mae: 19.6013
Epoch 7/200
13/13 [==============================] - 0s 4ms/step - loss: 14.9908 - mae: 14.9908
Epoch 8/200
13/13 [==============================] - 0s 4ms/step - loss: 18.0200 - mae: 18.0200
Epoch 9/200
13/13 [==============================] - 0s 4ms/step - loss: 18.0344 - mae: 18.0344
Epoch 10/200
13/13 [==============================] - 0s 4ms/step - loss: 20.0026 - mae: 20.0026
Epoch 11/200
13/13 [=================

In [35]:
# Evaluate model
boston_pricing_model.evaluate(tf.expand_dims(X_test, axis=1), y_test)

4/4 [==============================] - 0s 2ms/step - loss: 7.2920 - mae: 7.2920


[7.292031288146973, 7.292031288146973]